# Cấu hình chung
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id:
          new_generator_mappings: true
        show:
          sql: true
        format_sql: true
      hb2dll:
        auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

# Cấu hình cho môi trường phát triển cục bộ
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/appmonngon
    username: root
    password: S0nSandy93

# Cấu hình cho môi trường máy chủ (Railway)
---
spring:
  profiles: railway
  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:30091/railway
    username: root
    password: g31D2Dge4A4-efbDHfaaaAGC634AEa43
